modLoader="kotlinfml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/LibrarianLib/LibrarianLib/issues"
[[mods]]
modId="librarianlib"
version="@version@"
displayName="LibrarianLib"
# A URL to query for updates for this mod. See the JSON update specification <here>
# updateJSONURL="http://myurl.me/" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
# displayURL="http://example.com/" #optional
logoFile="icon.png"
# credits="Thanks for this example mod goes to Java"
# authors="Love, Cheese and small house plants" #optional
description='''
A collection of libraries designed to make creating great Minecraft mods easier.
'''
[[dependencies.librarianlib]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
[[dependencies.librarianlib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
